### ISSUE TITLE
Plexbmc Helper stopped when start playing audio

### ISSUE THREAD

**Issue by Baswazz** [hippojay/script.plexbmc.helper#6]
Debug Log:
http://pastebin.com/vnF4BHsX

19:33:01 121.996056 T:2830967872  NOTICE: == ENTER: PLAY ==
19:33:01 122.001877 T:2830967872  NOTICE: PleXBMC -> PLAY: We are playing a stream
19:33:01 122.009834 T:2830967872  NOTICE: ===== PLEXBMC STOP =====
19:33:01 122.117119 T:2830967872  NOTICE: Thread FileCache start, auto delete: false
19:33:02 122.923294 T:2900358208  NOTICE: Previous line repeats 1 times.
19:33:02 122.923531 T:2900358208  NOTICE: Thread BackgroundLoader start, auto delete: false
19:33:02 122.928436 T:2789024832  NOTICE: Thread PAPlayer start, auto delete: false
19:33:03 123.775833 T:2866803776   ERROR: Traceback (most recent call last):
19:33:03 123.776405 T:2866803776   ERROR:   File "/home/pi/.xbmc/addons/script.plexbmc.helper-3.4.2/default.py", line 115, in <module>
19:33:03 123.778519 T:2866803776   ERROR:     subMgr.notify()
19:33:03 123.784607 T:2866803776   ERROR:   File "/home/pi/.xbmc/addons/script.plexbmc.helper-3.4.2/resources/lib/subscribers.py", line 100, in notify
19:33:03 123.883705 T:2866803776   ERROR:     self.notifyServer(players)
19:33:03 123.884445 T:2866803776   ERROR:   File "/home/pi/.xbmc/addons/script.plexbmc.helper-3.4.2/resources/lib/subscribers.py", line 107, in notifyServer
19:33:03 123.885117 T:2866803776   ERROR:     info = self.playerprops[p.get('playerid')]
19:33:03 123.885658 T:2866803776   ERROR: KeyError: 0
19:33:03 123.886009 T:2866803776  NOTICE: None
19:33:03 123.906860 T:2866803776  NOTICE: PleXBMC Helper -> PleXBMC Helper has been stopped

I am running the latest Helix build for Raspberry Pi (Raspbmc):
http://forum.xbmc.org/showthread.php?tid=176043&pid=1809636#pid1809636

Plexbmc 3.4.6~beta3
Plexbmc Helper 3.4.2

Let me know if you need any more information

**Comment by dotted** [comment]
:+1:

**Comment by KlugFR** [comment]
Same issue for me.
Running CrystalBuntu 2.0 for AppleTV, with last stable PlexBMC from repo.

Is there a way to restart (CLI) the PlexBMC Helper?

**Comment by wickning1** [comment]
This should be fixed in 3.4.7.

**Comment by KlugFR** [comment]
Can PlexBMC.Helper 3.4.7 can be used with PlexBMC 3.6.x (or 4.0.0 beta)?

**Comment by hippojay** [comment]
Wickning1 is best to answer - but I just want to point out that plexbmc now has timeline support, which will clash with the helper timeline support. So you end up with two entries in the now playing/activty screen.  plexbmc can be set to disable monitoring, but we might just need to add a test into the helper also to check for plexbmc 4 or above and disable it by default.

**Comment by KlugFR** [comment]
I'm currently running Kodi 14 RC1 (not the latest I know but the one currently setup on my AppleTV runing OSMC/Crystalbuntu) with PlexBMC 3.6.1 and the new PlexBMC.Helper (3.4.7).

It's a headless setup, used to play lossless music.

I can now see the AppleTV in my Plex client (android), while I could not with the previous PlexBMC.Helper.
PlexBMC.Helper did not stop/crashed when music was played. Sounds like it works 8))

However, it's quite verbose in the kodi.log (several messages per second).

**Comment by KlugFR** [comment]
Another problem (maybe I should open another issue?): on the android Plex client, the "now playing" song shown is always the first song of the album (while in the kodi.log, PlexBMC.Helper knows/shows the correct song name).
Even if I select (direct play) another song of the album.

**Comment by wickning1** [comment]
You may have turned on plexbmc.helper debug output at some time in the past.  It is quite verbose.  You should be able to disable it in the plexbmc.helper settings (though I'm not sure how you do that headless).

I'll poke around at the song identification.

As for reporting what's playing back to the server, I originally patched plexbmc to stop reporting based on a window property (plexbmc.nowplaying.sent) because it was using the old reporting method instead of timeline. That flag presumably can still be observed, but I like the idea of simplifying helper if you've gotten it working in plexbmc.

**Comment by vulcanjedi** [comment]
Agreed is there a way to cycle this service from the command line?
