### ISSUE TITLE
Skript error on kodi 

### ISSUE THREAD

**Issue by wurtzelsepp** [hippojay/script.plexbmc.helper#9]
08:20:58 T:1569193952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: _ElementInterface instance has no attribute 'iter'
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexbmc.helper-3.4.2/default.py", line 47, in <module>
                                                from settings import settings
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexbmc.helper-3.4.2/resources/lib/settings.py", line 26, in <module>
                                                settings['client_name'] = getGUI('devicename')
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.plexbmc.helper-3.4.2/resources/lib/settings.py", line 16, in getGUI
                                                for elem in guidoc.iter(tag=name):
                                            AttributeError: _ElementInterface instance has no attribute 'iter'
                                            -->End of Python script error report<--
08:20:58 T:1579486208   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
08:20:58 T:1579486208   DEBUG: Window DialogKaiToast.xml was already loaded

**Comment by wickning1** [comment]
This shouldn't happen any more, using a different XML parser.
